version: '3.8'

services:
    container:
#        image: 'kohirens/circleci-go:${BUILD_VER:-dev}'
        image: 'kohirens/circleci-go:${BUILD_VER:-dev}'
        build:
            dockerfile: 'Dockerfile'
            context: '.'
        command: start.sh